
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: Omar Zahir's Arduino Project!
description: INSPIRE 1AO3: Electronics For The Rest Of Us
